version: '3.8'

services:

  web:
    build: .
    container_name: flask_web
    expose:
      - 8000

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web 



