version: "3.8"

services:
  app:
    build: ./app
    environment:
      REDIS_HOST: redis
      MYSQL_HOST: mysql
    depends_on:
      - redis
      - mysql

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app 

  redis:
    image: redis:alpine

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
