version: 3.8

services:
app:
  build: ./app
  environment:
    REDIS_HOST: redis
    MYSQL_HOST: mysql
  depends_on:
    - redis
    - mysql


nginx:
  image: nginx:alpine
  ports:
    - "8080:80"
  volumes:
    - ./nginx/nginx.conf
  depends_on:
    - app 

mysql:
  image: mysql:8.0
  environment:
    MYSQL_ROOT_PASSWORD: rootpass
    MYSQL_DATABASE: testdb
  volumes:
    - mysql-data:/var/lib/mysql
redis:
  image: redis:alpine

volumes:
  mysql-data:
