# Stage 1: Build stage
FROM python:3.12-slim AS builder

WORKDIR /app
COPY . .
RUN pip install --target=/app/deps -r requirements.txt || true
## || true > "If the previous command fails, ignore the error and continue."

#Stage 2: Minimal runtime image
FROM python:3.12-alpine

WORKDIR /app

COPY --from=builder /app .
ENV PYTHONPATH=/app/deps

CMD [ "python", "app.py" ]

## docker run --rm -d --name app python-multistage tail -f /dev/null
## docker exec -it app sh